// Wails bindings for Go App methods
// These will be auto-generated by Wails during build

export interface HomeState {
  lastUpdateTime: string;
  lastUpdateError: string;
  isUpdating: boolean;
}

export interface AppUpdateState {
  currentVersion: string;
  latestVersion: string;
  lastCheckTime: string;
  updateAvailable: boolean;
  isCheckingForUpdate: boolean;
  isDownloadingUpdate: boolean;
  autoUpdateEnabled: boolean;
}

// Declare the window.go object
declare global {
  interface Window {
    go: {
      main: {
        App: {
          GetHomeState(): Promise<HomeState>;
          UpdateHeroesGrid(): Promise<void>;
          GetGridConfigPaths(): Promise<string[]>;
          AddGridConfigPath(path: string): Promise<void>;
          RemoveGridConfigPath(index: number): Promise<void>;
          OpenFileDialog(): Promise<string>;
          GetPositionsOrder(): Promise<string[]>;
          SetPositionsOrder(positions: string[]): Promise<void>;
          MovePositionUp(index: number): Promise<string[]>;
          MovePositionDown(index: number): Promise<string[]>;
          GetStartupEnabled(): Promise<boolean>;
          SetStartupEnabled(enabled: boolean): Promise<void>;
          IsStartupSupported(): Promise<boolean>;
          GetAppUpdateState(): Promise<AppUpdateState>;
          CheckForAppUpdate(): Promise<void>;
          DownloadAppUpdate(): Promise<void>;
          GetAutoUpdateEnabled(): Promise<boolean>;
          SetAutoUpdateEnabled(enabled: boolean): Promise<void>;
        };
      };
    };
  }
}

// Export functions that call the Go bindings
export function GetHomeState(): Promise<HomeState> {
  return window.go.main.App.GetHomeState();
}

export function UpdateHeroesGrid(): Promise<void> {
  return window.go.main.App.UpdateHeroesGrid();
}

export function GetGridConfigPaths(): Promise<string[]> {
  return window.go.main.App.GetGridConfigPaths();
}

export function AddGridConfigPath(path: string): Promise<void> {
  return window.go.main.App.AddGridConfigPath(path);
}

export function RemoveGridConfigPath(index: number): Promise<void> {
  return window.go.main.App.RemoveGridConfigPath(index);
}

export function OpenFileDialog(): Promise<string> {
  return window.go.main.App.OpenFileDialog();
}

export function GetPositionsOrder(): Promise<string[]> {
  return window.go.main.App.GetPositionsOrder();
}

export function SetPositionsOrder(positions: string[]): Promise<void> {
  return window.go.main.App.SetPositionsOrder(positions);
}

export function MovePositionUp(index: number): Promise<string[]> {
  return window.go.main.App.MovePositionUp(index);
}

export function MovePositionDown(index: number): Promise<string[]> {
  return window.go.main.App.MovePositionDown(index);
}

export function GetStartupEnabled(): Promise<boolean> {
  return window.go.main.App.GetStartupEnabled();
}

export function SetStartupEnabled(enabled: boolean): Promise<void> {
  return window.go.main.App.SetStartupEnabled(enabled);
}

export function IsStartupSupported(): Promise<boolean> {
  return window.go.main.App.IsStartupSupported();
}

export function GetAppUpdateState(): Promise<AppUpdateState> {
  return window.go.main.App.GetAppUpdateState();
}

export function CheckForAppUpdate(): Promise<void> {
  return window.go.main.App.CheckForAppUpdate();
}

export function DownloadAppUpdate(): Promise<void> {
  return window.go.main.App.DownloadAppUpdate();
}

export function GetAutoUpdateEnabled(): Promise<boolean> {
  return window.go.main.App.GetAutoUpdateEnabled();
}

export function SetAutoUpdateEnabled(enabled: boolean): Promise<void> {
  return window.go.main.App.SetAutoUpdateEnabled(enabled);
}
