// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddGridConfigPath(arg1:string):Promise<void>;

export function CheckForAppUpdate():Promise<void>;

export function DownloadAppUpdate():Promise<void>;

export function GetAppUpdateState():Promise<main.AppUpdateState>;

export function GetAutoUpdateEnabled():Promise<boolean>;

export function GetGridConfigPaths():Promise<Array<string>>;

export function GetHomeState():Promise<main.HomeState>;

export function GetPositionsOrder():Promise<Array<string>>;

export function GetStartupEnabled():Promise<boolean>;

export function IsStartupSupported():Promise<boolean>;

export function MovePositionDown(arg1:number):Promise<Array<string>>;

export function MovePositionUp(arg1:number):Promise<Array<string>>;

export function OpenFileDialog():Promise<string>;

export function RemoveGridConfigPath(arg1:number):Promise<void>;

export function SetAutoUpdateEnabled(arg1:boolean):Promise<void>;

export function SetPositionsOrder(arg1:Array<string>):Promise<void>;

export function SetStartupEnabled(arg1:boolean):Promise<void>;

export function UpdateHeroesLayout():Promise<void>;
