// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AddHeroesLayoutFile(arg1:string):Promise<void>;

export function CheckForAppUpdate():Promise<void>;

export function DownloadAppUpdate():Promise<void>;

export function GetAppUpdateState():Promise<main.AppUpdateState>;

export function GetHeroesLayoutFiles():Promise<Array<config.FileConfig>>;

export function GetPositions():Promise<Array<config.PositionConfig>>;

export function GetStartupEnabled():Promise<boolean>;

export function IsStartupSupported():Promise<boolean>;

export function OpenFileDialog():Promise<string>;

export function RemoveHeroesLayoutFile(arg1:number):Promise<void>;

export function SetHeroesLayoutFileEnabled(arg1:number,arg2:boolean):Promise<void>;

export function SetPositionEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetPositions(arg1:Array<config.PositionConfig>):Promise<void>;

export function SetStartupEnabled(arg1:boolean):Promise<void>;

export function UpdateHeroesLayout():Promise<void>;
