// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGridConfigPath(arg1) {
  return window['go']['main']['App']['AddGridConfigPath'](arg1);
}

export function CheckForAppUpdate() {
  return window['go']['main']['App']['CheckForAppUpdate']();
}

export function DownloadAppUpdate() {
  return window['go']['main']['App']['DownloadAppUpdate']();
}

export function GetAppUpdateState() {
  return window['go']['main']['App']['GetAppUpdateState']();
}

export function GetAutoUpdateEnabled() {
  return window['go']['main']['App']['GetAutoUpdateEnabled']();
}

export function GetGridConfigPaths() {
  return window['go']['main']['App']['GetGridConfigPaths']();
}

export function GetHomeState() {
  return window['go']['main']['App']['GetHomeState']();
}

export function GetPositionsOrder() {
  return window['go']['main']['App']['GetPositionsOrder']();
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function IsStartupSupported() {
  return window['go']['main']['App']['IsStartupSupported']();
}

export function MovePositionDown(arg1) {
  return window['go']['main']['App']['MovePositionDown'](arg1);
}

export function MovePositionUp(arg1) {
  return window['go']['main']['App']['MovePositionUp'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RemoveGridConfigPath(arg1) {
  return window['go']['main']['App']['RemoveGridConfigPath'](arg1);
}

export function SetAutoUpdateEnabled(arg1) {
  return window['go']['main']['App']['SetAutoUpdateEnabled'](arg1);
}

export function SetPositionsOrder(arg1) {
  return window['go']['main']['App']['SetPositionsOrder'](arg1);
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}

export function UpdateHeroesGrid() {
  return window['go']['main']['App']['UpdateHeroesGrid']();
}
