// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHeroesLayoutFile(arg1) {
  return window['go']['main']['App']['AddHeroesLayoutFile'](arg1);
}

export function CheckForAppUpdate() {
  return window['go']['main']['App']['CheckForAppUpdate']();
}

export function DownloadAppUpdate() {
  return window['go']['main']['App']['DownloadAppUpdate']();
}

export function GetAppUpdateState() {
  return window['go']['main']['App']['GetAppUpdateState']();
}

export function GetD2PTConfig() {
  return window['go']['main']['App']['GetD2PTConfig']();
}

export function GetHeroesLayoutFiles() {
  return window['go']['main']['App']['GetHeroesLayoutFiles']();
}

export function GetHeroesPerRow() {
  return window['go']['main']['App']['GetHeroesPerRow']();
}

export function GetPositions() {
  return window['go']['main']['App']['GetPositions']();
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function GetSteamAccounts() {
  return window['go']['main']['App']['GetSteamAccounts']();
}

export function GetSteamConfig() {
  return window['go']['main']['App']['GetSteamConfig']();
}

export function IsStartupSupported() {
  return window['go']['main']['App']['IsStartupSupported']();
}

export function IsSteamPathValid() {
  return window['go']['main']['App']['IsSteamPathValid']();
}

export function OpenAppDirectory() {
  return window['go']['main']['App']['OpenAppDirectory']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RemoveHeroesLayoutFile(arg1) {
  return window['go']['main']['App']['RemoveHeroesLayoutFile'](arg1);
}

export function RescanSteamAccounts() {
  return window['go']['main']['App']['RescanSteamAccounts']();
}

export function SetAutoEnableNewAccounts(arg1) {
  return window['go']['main']['App']['SetAutoEnableNewAccounts'](arg1);
}

export function SetD2PTPeriod(arg1) {
  return window['go']['main']['App']['SetD2PTPeriod'](arg1);
}

export function SetHeroesLayoutFileEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetHeroesLayoutFileEnabled'](arg1, arg2);
}

export function SetHeroesPerRow(arg1) {
  return window['go']['main']['App']['SetHeroesPerRow'](arg1);
}

export function SetPositionEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPositionEnabled'](arg1, arg2);
}

export function SetPositions(arg1) {
  return window['go']['main']['App']['SetPositions'](arg1);
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}

export function SetSteamAccountEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetSteamAccountEnabled'](arg1, arg2);
}

export function SetSteamPath(arg1) {
  return window['go']['main']['App']['SetSteamPath'](arg1);
}

export function UpdateHeroesLayout() {
  return window['go']['main']['App']['UpdateHeroesLayout']();
}
