// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {steam} from '../models';

export function AddHeroesLayoutFile(arg1:string):Promise<void>;

export function CheckForAppUpdate():Promise<void>;

export function DownloadAppUpdate():Promise<void>;

export function GetAppUpdateState():Promise<main.AppUpdateState>;

export function GetD2PTConfig():Promise<config.D2PTConfig>;

export function GetHeroesLayoutFiles():Promise<Array<config.FileConfig>>;

export function GetHeroesPerRow():Promise<number>;

export function GetPositions():Promise<Array<config.PositionConfig>>;

export function GetStartupEnabled():Promise<boolean>;

export function GetSteamAccounts():Promise<Array<steam.SteamAccountView>>;

export function GetSteamConfig():Promise<config.SteamConfig>;

export function IsStartupSupported():Promise<boolean>;

export function IsSteamPathValid():Promise<boolean>;

export function OpenAppDirectory():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RemoveHeroesLayoutFile(arg1:string):Promise<void>;

export function RescanSteamAccounts():Promise<void>;

export function SetAutoEnableNewAccounts(arg1:boolean):Promise<void>;

export function SetD2PTPeriod(arg1:string):Promise<void>;

export function SetHeroesLayoutFileEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetHeroesPerRow(arg1:number):Promise<void>;

export function SetPositionEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetPositions(arg1:Array<config.PositionConfig>):Promise<void>;

export function SetStartupEnabled(arg1:boolean):Promise<void>;

export function SetSteamAccountEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetSteamPath(arg1:string):Promise<void>;

export function UpdateHeroesLayout():Promise<void>;
