// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHeroesLayoutFile(arg1) {
  return window['go']['main']['App']['AddHeroesLayoutFile'](arg1);
}

export function CheckForAppUpdate() {
  return window['go']['main']['App']['CheckForAppUpdate']();
}

export function DownloadAppUpdate() {
  return window['go']['main']['App']['DownloadAppUpdate']();
}

export function GetAppUpdateState() {
  return window['go']['main']['App']['GetAppUpdateState']();
}

export function GetAutoUpdateEnabled() {
  return window['go']['main']['App']['GetAutoUpdateEnabled']();
}

export function GetHeroesLayoutFiles() {
  return window['go']['main']['App']['GetHeroesLayoutFiles']();
}

export function GetIsUpdatingLayout() {
  return window['go']['main']['App']['GetIsUpdatingLayout']();
}

export function GetPositions() {
  return window['go']['main']['App']['GetPositions']();
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function IsStartupSupported() {
  return window['go']['main']['App']['IsStartupSupported']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RemoveHeroesLayoutFile(arg1) {
  return window['go']['main']['App']['RemoveHeroesLayoutFile'](arg1);
}

export function SetAutoUpdateEnabled(arg1) {
  return window['go']['main']['App']['SetAutoUpdateEnabled'](arg1);
}

export function SetHeroesLayoutFileEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetHeroesLayoutFileEnabled'](arg1, arg2);
}

export function SetPositionEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPositionEnabled'](arg1, arg2);
}

export function SetPositions(arg1) {
  return window['go']['main']['App']['SetPositions'](arg1);
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}

export function UpdateHeroesLayout() {
  return window['go']['main']['App']['UpdateHeroesLayout']();
}
